name: Run Monitoring Script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  run-monitoring:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
        
    - name: Setup Conda and Run Monitoring
      run: |
        conda init bash
        source ~/.bashrc
        conda activate monitoring
        pip install -r requirements.txt
        python3 run_example.py
      shell: bash -l {0}